# Generated by Django 2.0.4 on 2019-12-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_product_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('addrress', models.CharField(max_length=150)),
            ],
        ),
    ]
