# Generated by Django 2.0.4 on 2019-12-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_auto_20191206_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateruser',
            name='userphone',
            field=models.CharField(default='', max_length=20, verbose_name='userphone'),
        ),
        migrations.AlterField(
            model_name='wateruser',
            name='addrress',
            field=models.CharField(max_length=150, verbose_name='addrress'),
        ),
        migrations.AlterField(
            model_name='wateruser',
            name='username',
            field=models.CharField(max_length=100, verbose_name='username'),
        ),
    ]
