# Generated by Django 2.0.4 on 2019-12-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_auto_20191206_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user',
        ),
    ]
